# Generated by Django 4.0.5 on 2022-06-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subTitle', models.CharField(max_length=20)),
                ('autorName', models.CharField(max_length=10)),
                ('autorSurname', models.CharField(max_length=15)),
                ('cuerpo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
