# Generated by Django 4.0.5 on 2022-06-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0004_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='fecha',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
