# Generated by Django 4.0.5 on 2022-06-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0005_blog_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
